version: 0.2
env:
  secrets-manager:
    DOCKERHUB_PASS: "/dockerhub/credentials:pass"
    DOCKERHUB_USERNAME: "/dockerhub/credentials:user"
phases: 
  pre_build: 
    commands: 
    - echo Logging in to Amazon ECR....
    - aws --version
    - AWS_DEFAULT_REGION=sa-east-1
    - AWS_ACCOUNT_ID=270167558056
    - APPLICATION_NAME=futechat
    - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APPLICATION_NAME
    - echo $AWS_DEFAULT_REGION
    - echo $AWS_ACCOUNT_ID
    - echo $APPLICATION_NAME
    - echo $REPOSITORY_URI
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS     
    # Get commit hash value to tag the image
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
    # Replace with your application name
    # Replace with this 435320931996.dkr.ecr.ap-south-1.amazonaws.com to your repository URI
  build: 
    commands: 
    - echo Build started on `date` 
    - echo Building the Docker image... 
    - docker build -t $APPLICATION_NAME:$IMAGE_TAG .
    - docker tag $APPLICATION_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG 
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pushing to repo
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Writing image definitions file... 
    # Give your container name
    - printf '[{"name":"futechat", "imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json