cloud:
  aws:
    region:
      static: sa-east-1
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
    br:
      com:
        futechat:
          discord:
            bot:
              config:
                GlobalCommandRegistrar: trace
          
          
apiFootball:
  url: https://api-football-v1.p.rapidapi.com/v3
  host: api-football-v1.p.rapidapi.com
  
management:
  endpoints:
    web:
      exposure:
        include: health