cloud:
  aws:
    region:
      static: sa-east-1
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
apiFootball:
  url: http://localhost:2345