spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 60000
    lettuce:
      pool.max-active: 8
      pool.max-idle: 8
      pool.max-wait: -1
      pool.min-idle: 0
  cache:
    type: redis
    
apiFootball:
  url: https://api-football-v1.p.rapidapi.com/v3
  host: api-football-v1.p.rapidapi.com
  
logging:
  group:
    utils: br.com.futechat.discord.utils
  level:
    utils: TRACE    